const myArray = [
    {
      "Code_géographique": "01001",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "L'Abergement-Clémenciat",
      "Population_en_2017": 776,
      "Pop_014_ans_2017": 162,
      "Pop_par_ans_2017": 12,
      "Pop_017_ans_2017": 196,
      "Popu_possible_voté": 580,
      "% Popu ref": 35,
      "Pop_Negatif": 545,
      "Pop_Positif": 615,
      "Libellé_de_la_commune": "L'Abergement-Clémenciat",
      "Inscrits": 598,
      "Nbr_Inscrits_Médians": -18,
      "Nbr_Inscrit_Négatif": -53,
      "Nbr_Inscrit_Positif": 17,
      "Recap": 3,
      "Abstentions": 100,
      "Abs_Ins": 16.72,
      "Votants": 498,
      "Vot_Ins": 83.28,
      "Blancs": 5,
      "Blancs_Ins": 0.84,
      "Nuls": 40,
      "Nuls_Ins": 6.69,
      "Exprimés": 453,
      "Exp_Ins": 75.75,
      "Nom": "MACRON",
      "Voix": 272,
      "Voix_Ins_Macron": 45.48,
      "Nom__1": "LE PEN",
      "Voix__1": 181,
      "Voix_Ins_Lepen": 30.27,
      "Pop_Négatif_Abstentions": "",
      "Pop_Négatif_Abs_Ins": "",
      "Pop_Négatif_Vot_Ins": "",
      "Pop_Négatif_Exp_Ins": "",
      "Pop_Négatif_BlancNul_Ins": "",
      "Nom__2": "",
      "Pop_Négatif_Voix_Ins_Macron": "",
      "Nom__3": "",
      "Pop_Négatif_Voix_Ins_Lepen": "",
      "Pop_Médiane_Abstentions": 82,
      "Pop_Médiane_Abs_Ins": 14.11,
      "Pop_Médiane_Vot_Ins": 85.89,
      "Pop_Médiane_Exp_Ins": 78.13,
      "Pop_Médiane_BlancNul_Ins": 7.76,
      "Nom__4": "MACRON",
      "Pop_Médiane_Voix_Ins_Macron": 46.91,
      "Nom__5": "LE PEN",
      "Pop_Médiane_Voix_Ins_Lepen": 31.22,
      "Pop_Positif_Abstentions": 117,
      "Pop_Positif_Abs_Ins": 18.97,
      "Pop_Positif_Vot_Ins": 81.03,
      "Pop_Positif_Exp_Ins": 73.7,
      "Pop_Positif_BlancNul_Ins": 7.32,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 44.26,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 29.45,
      "Rejet_Pop_Officiel": 24.25,
      "Rejet_Pop_Basse": "",
      "Rejet_Pop_Médiane": 21.87,
      "Rejet_Pop_Positif": 26.3
    },
    {
      "Code_géographique": "01002",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "L'Abergement-de-Varey",
      "Population_en_2017": 248,
      "Pop_014_ans_2017": 56,
      "Pop_par_ans_2017": 4,
      "Pop_017_ans_2017": 68,
      "Popu_possible_voté": 180,
      "% Popu ref": 15,
      "Pop_Negatif": 165,
      "Pop_Positif": 194,
      "Libellé_de_la_commune": "L'Abergement-de-Varey",
      "Inscrits": 209,
      "Nbr_Inscrits_Médians": -29,
      "Nbr_Inscrit_Négatif": -44,
      "Nbr_Inscrit_Positif": -15,
      "Recap": 1,
      "Abstentions": 32,
      "Abs_Ins": 15.31,
      "Votants": 177,
      "Vot_Ins": 84.69,
      "Blancs": 21,
      "Blancs_Ins": 10.05,
      "Nuls": 6,
      "Nuls_Ins": 2.87,
      "Exprimés": 150,
      "Exp_Ins": 71.77,
      "Nom": "MACRON",
      "Voix": 93,
      "Voix_Ins_Macron": 44.5,
      "Nom__1": "LE PEN",
      "Voix__1": 57,
      "Voix_Ins_Lepen": 27.27,
      "Pop_Négatif_Abstentions": "",
      "Pop_Négatif_Abs_Ins": "",
      "Pop_Négatif_Vot_Ins": "",
      "Pop_Négatif_Exp_Ins": "",
      "Pop_Négatif_BlancNul_Ins": "",
      "Nom__2": "",
      "Pop_Négatif_Voix_Ins_Macron": "",
      "Nom__3": "",
      "Pop_Négatif_Voix_Ins_Lepen": "",
      "Pop_Médiane_Abstentions": "",
      "Pop_Médiane_Abs_Ins": "",
      "Pop_Médiane_Vot_Ins": "",
      "Pop_Médiane_Exp_Ins": "",
      "Pop_Médiane_BlancNul_Ins": "",
      "Nom__4": "",
      "Pop_Médiane_Voix_Ins_Macron": "",
      "Nom__5": "",
      "Pop_Médiane_Voix_Ins_Lepen": "",
      "Pop_Positif_Abstentions": "",
      "Pop_Positif_Abs_Ins": "",
      "Pop_Positif_Vot_Ins": "",
      "Pop_Positif_Exp_Ins": "",
      "Pop_Positif_BlancNul_Ins": "",
      "Nom__6": "",
      "Pop_Positif_Voix_Ins_Macron": "",
      "Nom__7": "",
      "Pop_Positif_Voix_Ins_Lepen": "",
      "Rejet_Pop_Officiel": 28.23,
      "Rejet_Pop_Basse": "",
      "Rejet_Pop_Médiane": "",
      "Rejet_Pop_Positif": ""
    },
    {
      "Code_géographique": "01004",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "Ambérieu-en-Bugey",
      "Population_en_2017": 14035,
      "Pop_014_ans_2017": 2726,
      "Pop_par_ans_2017": 195,
      "Pop_017_ans_2017": 3310,
      "Popu_possible_voté": 10725,
      "% Popu ref": 215,
      "Pop_Negatif": 10511,
      "Pop_Positif": 10940,
      "Libellé_de_la_commune": "Ambérieu-en-Bugey",
      "Inscrits": 8586,
      "Nbr_Inscrits_Médians": 2139,
      "Nbr_Inscrit_Négatif": 1925,
      "Nbr_Inscrit_Positif": 2354,
      "Recap": 4,
      "Abstentions": 2312,
      "Abs_Ins": 26.93,
      "Votants": 6274,
      "Vot_Ins": 73.07,
      "Blancs": 601,
      "Blancs_Ins": 7,
      "Nuls": 217,
      "Nuls_Ins": 2.53,
      "Exprimés": 5456,
      "Exp_Ins": 63.55,
      "Nom": "MACRON",
      "Voix": 3213,
      "Voix_Ins_Macron": 37.42,
      "Nom__1": "LE PEN",
      "Voix__1": 2243,
      "Voix_Ins_Lepen": 26.12,
      "Pop_Négatif_Abstentions": 4237,
      "Pop_Négatif_Abs_Ins": 40.31,
      "Pop_Négatif_Vot_Ins": 59.69,
      "Pop_Négatif_Exp_Ins": 51.91,
      "Pop_Négatif_BlancNul_Ins": 7.78,
      "Nom__2": "MACRON",
      "Pop_Négatif_Voix_Ins_Macron": 30.57,
      "Nom__3": "LE PEN",
      "Pop_Négatif_Voix_Ins_Lepen": 21.34,
      "Pop_Médiane_Abstentions": 4451,
      "Pop_Médiane_Abs_Ins": 41.5,
      "Pop_Médiane_Vot_Ins": 58.5,
      "Pop_Médiane_Exp_Ins": 50.87,
      "Pop_Médiane_BlancNul_Ins": 7.63,
      "Nom__4": "MACRON",
      "Pop_Médiane_Voix_Ins_Macron": 29.96,
      "Nom__5": "LE PEN",
      "Pop_Médiane_Voix_Ins_Lepen": 20.91,
      "Pop_Positif_Abstentions": 4666,
      "Pop_Positif_Abs_Ins": 42.65,
      "Pop_Positif_Vot_Ins": 57.35,
      "Pop_Positif_Exp_Ins": 49.87,
      "Pop_Positif_BlancNul_Ins": 7.48,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 29.37,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 20.5,
      "Rejet_Pop_Officiel": 36.45,
      "Rejet_Pop_Basse": 48.09,
      "Rejet_Pop_Médiane": 49.13,
      "Rejet_Pop_Positif": 50.13
    },
    {
      "Code_géographique": "01005",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "Ambérieux-en-Dombes",
      "Population_en_2017": 1689,
      "Pop_014_ans_2017": 344,
      "Pop_par_ans_2017": 25,
      "Pop_017_ans_2017": 418,
      "Popu_possible_voté": 1271,
      "% Popu ref": 57,
      "Pop_Negatif": 1214,
      "Pop_Positif": 1328,
      "Libellé_de_la_commune": "Ambérieux-en-Dombes",
      "Inscrits": 1172,
      "Nbr_Inscrits_Médians": 99,
      "Nbr_Inscrit_Négatif": 42,
      "Nbr_Inscrit_Positif": 156,
      "Recap": 4,
      "Abstentions": 259,
      "Abs_Ins": 22.1,
      "Votants": 913,
      "Vot_Ins": 77.9,
      "Blancs": 77,
      "Blancs_Ins": 6.57,
      "Nuls": 24,
      "Nuls_Ins": 2.05,
      "Exprimés": 812,
      "Exp_Ins": 69.28,
      "Nom": "MACRON",
      "Voix": 423,
      "Voix_Ins_Macron": 36.09,
      "Nom__1": "LE PEN",
      "Voix__1": 389,
      "Voix_Ins_Lepen": 33.19,
      "Pop_Négatif_Abstentions": 301,
      "Pop_Négatif_Abs_Ins": 24.8,
      "Pop_Négatif_Vot_Ins": 75.2,
      "Pop_Négatif_Exp_Ins": 66.88,
      "Pop_Négatif_BlancNul_Ins": 8.32,
      "Nom__2": "MACRON",
      "Pop_Négatif_Voix_Ins_Macron": 34.84,
      "Nom__3": "LE PEN",
      "Pop_Négatif_Voix_Ins_Lepen": 32.04,
      "Pop_Médiane_Abstentions": 358,
      "Pop_Médiane_Abs_Ins": 28.18,
      "Pop_Médiane_Vot_Ins": 71.82,
      "Pop_Médiane_Exp_Ins": 63.87,
      "Pop_Médiane_BlancNul_Ins": 7.94,
      "Nom__4": "MACRON",
      "Pop_Médiane_Voix_Ins_Macron": 33.27,
      "Nom__5": "LE PEN",
      "Pop_Médiane_Voix_Ins_Lepen": 30.6,
      "Pop_Positif_Abstentions": 415,
      "Pop_Positif_Abs_Ins": 31.27,
      "Pop_Positif_Vot_Ins": 68.73,
      "Pop_Positif_Exp_Ins": 61.12,
      "Pop_Positif_BlancNul_Ins": 7.6,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 31.84,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 29.28,
      "Rejet_Pop_Officiel": 30.72,
      "Rejet_Pop_Basse": 33.12,
      "Rejet_Pop_Médiane": 36.13,
      "Rejet_Pop_Positif": 38.88
    },
    {
      "Code_géographique": "01006",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "Ambléon",
      "Population_en_2017": 111,
      "Pop_014_ans_2017": 12,
      "Pop_par_ans_2017": 1,
      "Pop_017_ans_2017": 15,
      "Popu_possible_voté": 96,
      "% Popu ref": 8,
      "Pop_Negatif": 88,
      "Pop_Positif": 104,
      "Libellé_de_la_commune": "Ambléon",
      "Inscrits": 99,
      "Nbr_Inscrits_Médians": -3,
      "Nbr_Inscrit_Négatif": -11,
      "Nbr_Inscrit_Positif": 5,
      "Recap": 2,
      "Abstentions": 23,
      "Abs_Ins": 23.23,
      "Votants": 76,
      "Vot_Ins": 76.77,
      "Blancs": 17,
      "Blancs_Ins": 17.17,
      "Nuls": 0,
      "Nuls_Ins": 0,
      "Exprimés": 59,
      "Exp_Ins": 59.6,
      "Nom": "MACRON",
      "Voix": 30,
      "Voix_Ins_Macron": 30.3,
      "Nom__1": "LE PEN",
      "Voix__1": 29,
      "Voix_Ins_Lepen": 29.29,
      "Pop_Négatif_Abstentions": "",
      "Pop_Négatif_Abs_Ins": "",
      "Pop_Négatif_Vot_Ins": "",
      "Pop_Négatif_Exp_Ins": "",
      "Pop_Négatif_BlancNul_Ins": "",
      "Nom__2": "",
      "Pop_Négatif_Voix_Ins_Macron": "",
      "Nom__3": "",
      "Pop_Négatif_Voix_Ins_Lepen": "",
      "Pop_Médiane_Abstentions": "",
      "Pop_Médiane_Abs_Ins": "",
      "Pop_Médiane_Vot_Ins": "",
      "Pop_Médiane_Exp_Ins": "",
      "Pop_Médiane_BlancNul_Ins": "",
      "Nom__4": "",
      "Pop_Médiane_Voix_Ins_Macron": "",
      "Nom__5": "",
      "Pop_Médiane_Voix_Ins_Lepen": "",
      "Pop_Positif_Abstentions": 28,
      "Pop_Positif_Abs_Ins": 0,
      "Pop_Positif_Vot_Ins": 73.01,
      "Pop_Positif_Exp_Ins": 56.68,
      "Pop_Positif_BlancNul_Ins": 0,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 28.82,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 27.86,
      "Rejet_Pop_Officiel": 40.4,
      "Rejet_Pop_Basse": "",
      "Rejet_Pop_Médiane": "",
      "Rejet_Pop_Positif": 43.32
    },
    {
      "Code_géographique": "01007",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "Ambronay",
      "Population_en_2017": 2726,
      "Pop_014_ans_2017": 608,
      "Pop_par_ans_2017": 43,
      "Pop_017_ans_2017": 738,
      "Popu_possible_voté": 1988,
      "% Popu ref": 70,
      "Pop_Negatif": 1919,
      "Pop_Positif": 2058,
      "Libellé_de_la_commune": "Ambronay",
      "Inscrits": 1880,
      "Nbr_Inscrits_Médians": 108,
      "Nbr_Inscrit_Négatif": 39,
      "Nbr_Inscrit_Positif": 178,
      "Recap": 4,
      "Abstentions": 336,
      "Abs_Ins": 17.87,
      "Votants": 1544,
      "Vot_Ins": 82.13,
      "Blancs": 138,
      "Blancs_Ins": 7.34,
      "Nuls": 31,
      "Nuls_Ins": 1.65,
      "Exprimés": 1375,
      "Exp_Ins": 73.14,
      "Nom": "MACRON",
      "Voix": 774,
      "Voix_Ins_Macron": 41.17,
      "Nom__1": "LE PEN",
      "Voix__1": 601,
      "Voix_Ins_Lepen": 31.97,
      "Pop_Négatif_Abstentions": 375,
      "Pop_Négatif_Abs_Ins": 19.53,
      "Pop_Négatif_Vot_Ins": 80.47,
      "Pop_Négatif_Exp_Ins": 71.66,
      "Pop_Négatif_BlancNul_Ins": 8.81,
      "Nom__2": "MACRON",
      "Pop_Négatif_Voix_Ins_Macron": 40.34,
      "Nom__3": "LE PEN",
      "Pop_Négatif_Voix_Ins_Lepen": 31.32,
      "Pop_Médiane_Abstentions": 444,
      "Pop_Médiane_Abs_Ins": 22.35,
      "Pop_Médiane_Vot_Ins": 77.65,
      "Pop_Médiane_Exp_Ins": 69.16,
      "Pop_Médiane_BlancNul_Ins": 8.5,
      "Nom__4": "MACRON",
      "Pop_Médiane_Voix_Ins_Macron": 38.93,
      "Nom__5": "LE PEN",
      "Pop_Médiane_Voix_Ins_Lepen": 30.23,
      "Pop_Positif_Abstentions": 514,
      "Pop_Positif_Abs_Ins": 24.97,
      "Pop_Positif_Vot_Ins": 75.03,
      "Pop_Positif_Exp_Ins": 66.82,
      "Pop_Positif_BlancNul_Ins": 8.21,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 37.61,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 29.2,
      "Rejet_Pop_Officiel": 26.86,
      "Rejet_Pop_Basse": 28.34,
      "Rejet_Pop_Médiane": 30.84,
      "Rejet_Pop_Positif": 33.18
    },
    {
      "Code_géographique": "01008",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "Ambutrix",
      "Population_en_2017": 752,
      "Pop_014_ans_2017": 136,
      "Pop_par_ans_2017": 10,
      "Pop_017_ans_2017": 166,
      "Popu_possible_voté": 586,
      "% Popu ref": 35,
      "Pop_Negatif": 551,
      "Pop_Positif": 621,
      "Libellé_de_la_commune": "Ambutrix",
      "Inscrits": 581,
      "Nbr_Inscrits_Médians": 5,
      "Nbr_Inscrit_Négatif": -30,
      "Nbr_Inscrit_Positif": 40,
      "Recap": 3,
      "Abstentions": 107,
      "Abs_Ins": 18.42,
      "Votants": 474,
      "Vot_Ins": 81.58,
      "Blancs": 39,
      "Blancs_Ins": 6.71,
      "Nuls": 16,
      "Nuls_Ins": 2.75,
      "Exprimés": 419,
      "Exp_Ins": 72.12,
      "Nom": "MACRON",
      "Voix": 252,
      "Voix_Ins_Macron": 43.37,
      "Nom__1": "LE PEN",
      "Voix__1": 167,
      "Voix_Ins_Lepen": 28.74,
      "Pop_Négatif_Abstentions": "",
      "Pop_Négatif_Abs_Ins": "",
      "Pop_Négatif_Vot_Ins": "",
      "Pop_Négatif_Exp_Ins": "",
      "Pop_Négatif_BlancNul_Ins": "",
      "Nom__2": "",
      "Pop_Négatif_Voix_Ins_Macron": "",
      "Nom__3": "",
      "Pop_Négatif_Voix_Ins_Lepen": "",
      "Pop_Médiane_Abstentions": 112,
      "Pop_Médiane_Abs_Ins": 19.15,
      "Pop_Médiane_Vot_Ins": 80.85,
      "Pop_Médiane_Exp_Ins": 71.46,
      "Pop_Médiane_BlancNul_Ins": 9.38,
      "Nom__4": "MACRON",
      "Pop_Médiane_Voix_Ins_Macron": 42.98,
      "Nom__5": "LE PEN",
      "Pop_Médiane_Voix_Ins_Lepen": 28.48,
      "Pop_Positif_Abstentions": 147,
      "Pop_Positif_Abs_Ins": 23.73,
      "Pop_Positif_Vot_Ins": 76.27,
      "Pop_Positif_Exp_Ins": 67.42,
      "Pop_Positif_BlancNul_Ins": 8.85,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 40.55,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 26.87,
      "Rejet_Pop_Officiel": 27.88,
      "Rejet_Pop_Basse": "",
      "Rejet_Pop_Médiane": 28.54,
      "Rejet_Pop_Positif": 32.58
    },
    {
      "Code_géographique": "01009",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "Andert-et-Condon",
      "Population_en_2017": 330,
      "Pop_014_ans_2017": 54,
      "Pop_par_ans_2017": 4,
      "Pop_017_ans_2017": 66,
      "Popu_possible_voté": 264,
      "% Popu ref": 21,
      "Pop_Negatif": 243,
      "Pop_Positif": 286,
      "Libellé_de_la_commune": "Andert-et-Condon",
      "Inscrits": 254,
      "Nbr_Inscrits_Médians": 10,
      "Nbr_Inscrit_Négatif": -11,
      "Nbr_Inscrit_Positif": 32,
      "Recap": 3,
      "Abstentions": 49,
      "Abs_Ins": 19.29,
      "Votants": 205,
      "Vot_Ins": 80.71,
      "Blancs": 6,
      "Blancs_Ins": 2.36,
      "Nuls": 23,
      "Nuls_Ins": 9.06,
      "Exprimés": 176,
      "Exp_Ins": 69.29,
      "Nom": "MACRON",
      "Voix": 119,
      "Voix_Ins_Macron": 46.85,
      "Nom__1": "LE PEN",
      "Voix__1": 57,
      "Voix_Ins_Lepen": 22.44,
      "Pop_Négatif_Abstentions": "",
      "Pop_Négatif_Abs_Ins": "",
      "Pop_Négatif_Vot_Ins": "",
      "Pop_Négatif_Exp_Ins": "",
      "Pop_Négatif_BlancNul_Ins": "",
      "Nom__2": "",
      "Pop_Négatif_Voix_Ins_Macron": "",
      "Nom__3": "",
      "Pop_Négatif_Voix_Ins_Lepen": "",
      "Pop_Médiane_Abstentions": 59,
      "Pop_Médiane_Abs_Ins": 22.48,
      "Pop_Médiane_Vot_Ins": 77.52,
      "Pop_Médiane_Exp_Ins": 66.55,
      "Pop_Médiane_BlancNul_Ins": 10.97,
      "Nom__4": "MACRON",
      "Pop_Médiane_Voix_Ins_Macron": 45,
      "Nom__5": "LE PEN",
      "Pop_Médiane_Voix_Ins_Lepen": 21.55,
      "Pop_Positif_Abstentions": 81,
      "Pop_Positif_Abs_Ins": 28.22,
      "Pop_Positif_Vot_Ins": 71.78,
      "Pop_Positif_Exp_Ins": 61.62,
      "Pop_Positif_BlancNul_Ins": 10.15,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 41.67,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 19.96,
      "Rejet_Pop_Officiel": 30.71,
      "Rejet_Pop_Basse": "",
      "Rejet_Pop_Médiane": 33.45,
      "Rejet_Pop_Positif": 38.38
    },
    {
      "Code_géographique": "01010",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "Anglefort",
      "Population_en_2017": 1115,
      "Pop_014_ans_2017": 265,
      "Pop_par_ans_2017": 19,
      "Pop_017_ans_2017": 322,
      "Popu_possible_voté": 793,
      "% Popu ref": 48,
      "Pop_Negatif": 746,
      "Pop_Positif": 841,
      "Libellé_de_la_commune": "Anglefort",
      "Inscrits": 739,
      "Nbr_Inscrits_Médians": 54,
      "Nbr_Inscrit_Négatif": 7,
      "Nbr_Inscrit_Positif": 102,
      "Recap": 4,
      "Abstentions": 145,
      "Abs_Ins": 19.62,
      "Votants": 594,
      "Vot_Ins": 80.38,
      "Blancs": 60,
      "Blancs_Ins": 8.12,
      "Nuls": 10,
      "Nuls_Ins": 1.35,
      "Exprimés": 524,
      "Exp_Ins": 70.91,
      "Nom": "MACRON",
      "Voix": 261,
      "Voix_Ins_Macron": 35.32,
      "Nom__1": "LE PEN",
      "Voix__1": 263,
      "Voix_Ins_Lepen": 35.59,
      "Pop_Négatif_Abstentions": 152,
      "Pop_Négatif_Abs_Ins": 20.33,
      "Pop_Négatif_Vot_Ins": 79.67,
      "Pop_Négatif_Exp_Ins": 70.28,
      "Pop_Négatif_BlancNul_Ins": 9.39,
      "Nom__2": "MACRON",
      "Pop_Négatif_Voix_Ins_Macron": 35,
      "Nom__3": "LE PEN",
      "Pop_Négatif_Voix_Ins_Lepen": 35.27,
      "Pop_Médiane_Abstentions": 199,
      "Pop_Médiane_Abs_Ins": 25.11,
      "Pop_Médiane_Vot_Ins": 74.89,
      "Pop_Médiane_Exp_Ins": 66.06,
      "Pop_Médiane_BlancNul_Ins": 8.82,
      "Nom__4": "MACRON",
      "Pop_Médiane_Voix_Ins_Macron": 32.9,
      "Nom__5": "LE PEN",
      "Pop_Médiane_Voix_Ins_Lepen": 33.16,
      "Pop_Positif_Abstentions": 247,
      "Pop_Positif_Abs_Ins": 29.35,
      "Pop_Positif_Vot_Ins": 70.65,
      "Pop_Positif_Exp_Ins": 62.32,
      "Pop_Positif_BlancNul_Ins": 8.33,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 31.04,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 31.28,
      "Rejet_Pop_Officiel": 29.09,
      "Rejet_Pop_Basse": 29.72,
      "Rejet_Pop_Médiane": 33.94,
      "Rejet_Pop_Positif": 37.68
    },
    {
      "Code_géographique": "01011",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "Apremont",
      "Population_en_2017": 376,
      "Pop_014_ans_2017": 87,
      "Pop_par_ans_2017": 6,
      "Pop_017_ans_2017": 106,
      "Popu_possible_voté": 270,
      "% Popu ref": 22,
      "Pop_Negatif": 249,
      "Pop_Positif": 292,
      "Libellé_de_la_commune": "Apremont",
      "Inscrits": 275,
      "Nbr_Inscrits_Médians": -5,
      "Nbr_Inscrit_Négatif": -26,
      "Nbr_Inscrit_Positif": 17,
      "Recap": 3,
      "Abstentions": 51,
      "Abs_Ins": 18.55,
      "Votants": 224,
      "Vot_Ins": 81.45,
      "Blancs": 30,
      "Blancs_Ins": 10.91,
      "Nuls": 11,
      "Nuls_Ins": 4,
      "Exprimés": 183,
      "Exp_Ins": 66.55,
      "Nom": "MACRON",
      "Voix": 88,
      "Voix_Ins_Macron": 32,
      "Nom__1": "LE PEN",
      "Voix__1": 95,
      "Voix_Ins_Lepen": 34.55,
      "Pop_Négatif_Abstentions": "",
      "Pop_Négatif_Abs_Ins": "",
      "Pop_Négatif_Vot_Ins": "",
      "Pop_Négatif_Exp_Ins": "",
      "Pop_Négatif_BlancNul_Ins": "",
      "Nom__2": "",
      "Pop_Négatif_Voix_Ins_Macron": "",
      "Nom__3": "",
      "Pop_Négatif_Voix_Ins_Lepen": "",
      "Pop_Médiane_Abstentions": 46,
      "Pop_Médiane_Abs_Ins": 17.15,
      "Pop_Médiane_Vot_Ins": 82.85,
      "Pop_Médiane_Exp_Ins": 67.69,
      "Pop_Médiane_BlancNul_Ins": 15.17,
      "Nom__4": "MACRON",
      "Pop_Médiane_Voix_Ins_Macron": 32.55,
      "Nom__5": "LE PEN",
      "Pop_Médiane_Voix_Ins_Lepen": 35.14,
      "Pop_Positif_Abstentions": 68,
      "Pop_Positif_Abs_Ins": 23.28,
      "Pop_Positif_Vot_Ins": 76.72,
      "Pop_Positif_Exp_Ins": 62.67,
      "Pop_Positif_BlancNul_Ins": 14.04,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 30.14,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 32.54,
      "Rejet_Pop_Officiel": 33.45,
      "Rejet_Pop_Basse": "",
      "Rejet_Pop_Médiane": 32.31,
      "Rejet_Pop_Positif": 37.33
    },
    {
      "Code_géographique": "01012",
      "Région": 84,
      "Département": "01",
      "Libellé_géographique": "Aranc",
      "Population_en_2017": 326,
      "Pop_014_ans_2017": 67,
      "Pop_par_ans_2017": 5,
      "Pop_017_ans_2017": 81,
      "Popu_possible_voté": 245,
      "% Popu ref": 20,
      "Pop_Negatif": 225,
      "Pop_Positif": 264,
      "Libellé_de_la_commune": "Aranc",
      "Inscrits": 278,
      "Nbr_Inscrits_Médians": -33,
      "Nbr_Inscrit_Négatif": -53,
      "Nbr_Inscrit_Positif": -14,
      "Recap": 2,
      "Abstentions": 66,
      "Abs_Ins": 23.74,
      "Votants": 212,
      "Vot_Ins": 76.26,
      "Blancs": 4,
      "Blancs_Ins": 1.44,
      "Nuls": 19,
      "Nuls_Ins": 6.83,
      "Exprimés": 189,
      "Exp_Ins": 67.99,
      "Nom": "MACRON",
      "Voix": 111,
      "Voix_Ins_Macron": 39.93,
      "Nom__1": "LE PEN",
      "Voix__1": 78,
      "Voix_Ins_Lepen": 28.06,
      "Pop_Négatif_Abstentions": "",
      "Pop_Négatif_Abs_Ins": "",
      "Pop_Négatif_Vot_Ins": "",
      "Pop_Négatif_Exp_Ins": "",
      "Pop_Négatif_BlancNul_Ins": "",
      "Nom__2": "",
      "Pop_Négatif_Voix_Ins_Macron": "",
      "Nom__3": "",
      "Pop_Négatif_Voix_Ins_Lepen": "",
      "Pop_Médiane_Abstentions": "",
      "Pop_Médiane_Abs_Ins": "",
      "Pop_Médiane_Vot_Ins": "",
      "Pop_Médiane_Exp_Ins": "",
      "Pop_Médiane_BlancNul_Ins": "",
      "Nom__4": "",
      "Pop_Médiane_Voix_Ins_Macron": "",
      "Nom__5": "",
      "Pop_Médiane_Voix_Ins_Lepen": "",
      "Pop_Positif_Abstentions": 52,
      "Pop_Positif_Abs_Ins": 0,
      "Pop_Positif_Vot_Ins": 80.24,
      "Pop_Positif_Exp_Ins": 71.53,
      "Pop_Positif_BlancNul_Ins": 0,
      "Nom__6": "MACRON",
      "Pop_Positif_Voix_Ins_Macron": 42.01,
      "Nom__7": "LE PEN",
      "Pop_Positif_Voix_Ins_Lepen": 29.52,
      "Rejet_Pop_Officiel": 32.01,
      "Rejet_Pop_Basse": "",
      "Rejet_Pop_Médiane": "",
      "Rejet_Pop_Positif": 28.47
    }
  ]
/*let name = '';
let code = '';
buildTable(myArray);

function buildTable(data){
    var nbc = myArray.length;
    console.log(nbc);
		
		for (let i = 0; i < data.length; i++){
     
      const rows = data[i];
      
      for (let ic = 0; ic < data.length; ic++){
        name = rows.Libellé_géographique;
        code = rows.Code_géographique;
        
      }
    console.log(name);
    console.log(code);
    
      

      
    
		}
  }
  const cats = ['Bill', 'Jeff', 'Pete', 'Biggles', 'Jasmin'];
let info = 'My cats are called ';
const para = document.querySelector('p');

for(let i = 0; i < cats.length; i++) {
  info += cats[i] + ', ';
}

para.textContent = info;

console.log(para);*/